# Generated by Django 3.2 on 2021-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['the_year']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['the_year']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['send_time']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['rating']},
        ),
        migrations.AlterModelOptions(
            name='skillset',
            options={'ordering': ['skillrank']},
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2),
        ),
        migrations.AddField(
            model_name='skillset',
            name='skillrank',
            field=models.PositiveIntegerField(blank=True, default=3, max_length=1),
        ),
    ]
