# Generated by Django 3.2 on 2021-07-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210706_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='fullName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
