# Generated by Django 3.2 on 2021-07-09 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_information_fullname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-the_year']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-the_year']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-send_time']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterModelOptions(
            name='skillset',
            options={'ordering': ['-skillrank']},
        ),
        migrations.CreateModel(
            name='FewWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
